### ISSUE TITLE
Error Invalid command name ''socket''

### ISSUE THREAD

**Issue by akangneo** [captbrando/pgMail#1]
ERROR:  invalid command name "socket"
            CONTEXT:  invalid command name "socket"
                while executing
            "socket $myHost $myPort"
                (procedure "__PLTcl_proc_17570" line 9)
                invoked from within

**Comment by captbrando** [comment]
Did you install pltcl or pltclu? The socket code is inside pltclu.

**Comment by MichaelDBA** [comment]
I see postgresql-pltcl-9.6 available to install, but where is pltclu? (on ubuntu 14.04 LTS).
I installed both:
createlang pltcl example
createlang pltclu example

I set the server to my smtp server name, smtp.1and1.com
and I set the database server to my example database, but still get similar errors:
```
example=# select pgmail('Send From <michael@vitalehouse.com>','Send To <michaeldba@sqlexec.com>', 'Subject goes here','Plaintext message body here.');
ERROR:  couldn't open socket: connection timed out
CONTEXT:  couldn't open socket: connection timed out
    while executing
"socket $myHost $myPort"
    (procedure "__PLTcl_proc_18041" line 15)
    invoked from within
"__PLTcl_proc_18041 {Send From <michael@vitalehouse.com>} {Send To <michaeldba@sqlexec.com>} {Subject goes here} {Plaintext message body here.} {}"
in PL/Tcl function "pgmail"
```

**Comment by captbrando** [comment]
Hey Michael! You want the pltcl package for Ubuntu. You just need to make sure when you use the createlang command that you pass pltclu as the language. They are both in the same package.

Also, you specify the SMTP port directly inside the pgMail function. Look at the top. Currently, there is no support for SMTP auth because of a number of challenges, so just pass it to your local mailserver on Ubuntu. You should have auto whitelisted connections to 127.0.0.1:25.

Thanks!
